# Generated by Django 5.2.17 on 2026-09-14 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareHomeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('senior_carer', 'Senior Carer'), ('carer', 'Carer'), ('administrator', 'Administrator')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.carehome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_home_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'care_home'), name='unique_user_care_home_membership')],
            },
        ),
    ]
